

drop table if exists Cow;
drop table if exists Dog;
drop table if exists Cat;
drop table if exists Horse;
drop table if exists Horse_type;

create table Cow(
	name bigserial PRIMARY KEY,
	milk_per_second int,
	breed int
);

insert into Cow(milk_per_second, breed) values
(100, 1),
(200, 2),
(250, 3),
(400, 2),
(300, 2),
(550, 3),
(120, 2),
(220, 2),
(340, 5),
(340, 2),
(350, 2),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(120, 2),
(120, 4),
(240, 4),
(245, 4),
(100, 1),
(200, 2),
(250, 3),
(400, 2),
(300, 2),
(550, 3),
(120, 2),
(220, 2),
(340, 5),
(340, 2),
(350, 2),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(120, 2),
(120, 4),
(240, 4),
(245, 4),
(200, 2),
(250, 3),
(400, 2),
(300, 2),
(550, 3),
(120, 2),
(220, 2),
(340, 5),
(340, 2),
(350, 2),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(120, 2),
(120, 4),
(240, 4),
(245, 4),
(200, 2),
(250, 3),
(400, 2),
(300, 2),
(550, 3),
(120, 2),
(220, 2),
(340, 5),
(340, 2),
(350, 2),
(3000, 7),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(120, 2),
(120, 4),
(240, 4),
(245, 4),
(200, 2),
(250, 3),
(400, 2),
(300, 2),
(550, 3),
(120, 2),
(220, 2),
(340, 5),
(340, 2),
(350, 2),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(550, 8),
(120, 2),
(350, 2),
(480, 7),
(100, 2),
(50, 2),
(30, 4),
(120, 2),
(120, 4),
(240, 4),
(870, 9),
(10000, 30);

create table Dog(
	name bigserial primary key
);

INSERT INTO Dog (name)
SELECT dogs.name
FROM generate_series(1, 100) AS dogs(name);

delete from Dog where name = 93;

create table Horse(
	name text,
	height int,
	code varchar(6) PRIMARY KEY,
	color text,
	sex text,
	age int
);

create table Horse_type(
	code varchar(3),
	name text
);

insert into Horse_type values
('abc', 'Ездовая'),
('dog', 'Тяжеловес'),
('cat', 'Скаковая'),
('dnd', 'Пони');

insert into Horse values
('Zebra the Horse of United States', 97, 'abc-8', 'white', 'female', 11),
('Knight the Samurai of Egypt', 147, 'dog-22', 'brown', 'male', 8),
('Horse the Lazy of Siberia', 151, 'dnd-2', 'black', 'male', 7),
('Knight the Mighty of Egypt', 193, 'dnd-47', 'white', 'female', 9),
('Zebra the Lazy of America', 106, 'dnd-12', 'brown', 'male', 19),
('Horse the Dragon of United States', 53, 'abc-29', 'white', 'male', 19),
('Horse the Ninja of United States', 60, 'dnd-11', 'brown', 'male', 18),
('Zebra the Lord of United States', 170, 'dog-57', 'white', 'male', 3),
('Zebra the Ruler of Siberia', 57, 'dog-23', 'black', 'male', 17),
('Zebra the Mighty of the kitchen', 111, 'abc-39', 'white', 'female', 5),
('Horse the Ninja of the kitchen', 83, 'dnd-25', 'brown', 'male', 3),
('Zebra the Pet of America', 189, 'cat-45', 'brown', 'male', 1),
('Horse the Samurai of Egypt', 91, 'cat-22', 'black', 'female', 17),
('Horse the Ninja of Siberia', 128, 'abc-31', 'white', 'female', 14),
('Zebra the Samurai of Egypt', 158, 'abc-27', 'brown', 'male', 19),
('Zebra the Samurai of United States', 130, 'dog-43', 'brown', 'female', 10),
('Horse the Lazy of Egypt', 144, 'dnd-44', 'black', 'female', 15),
('Knight the Samurai of America', 52, 'dnd-39', 'black', 'male', 9),
('Knight the Lazy of the kitchen', 62, 'dnd-21', 'white', 'male', 18),
('Knight the Horse of Japan', 187, 'abc-40', 'brown', 'female', 2),
('Zebra the Dragon of Egypt', 177, 'abc-34', 'brown', 'female', 2),
('Zebra the Pet of Japan', 86, 'cat-21', 'black', 'male', 4),
('Horse the Lazy of Egypt', 52, 'dog-51', 'brown', 'female', 14),
('Zebra the Ninja of Egypt', 76, 'dog-34', 'white', 'female', 12),
('Zebra the Mighty of the kitchen', 83, 'abc-38', 'brown', 'male', 1),
('Horse the Horse of Japan', 157, 'cat-7', 'white', 'male', 8),
('Zebra the Horse of America', 89, 'abc-45', 'white', 'male', 2),
('Horse the Mighty of Egypt', 140, 'dnd-1', 'brown', 'male', 1),
('Knight the Lazy of United States', 57, 'dog-31', 'white', 'male', 13),
('Knight the Lord of the streets', 149, 'cat-35', 'black', 'male', 15),
('Zebra the Dragon of Egypt', 121, 'dnd-24', 'white', 'male', 15),
('Zebra the Dragon of the kitchen', 87, 'abc-21', 'black', 'female', 1),
('Zebra the Ruler of United States', 120, 'dnd-10', 'brown', 'female', 5),
('Horse the Ninja of United States', 196, 'abc-18', 'black', 'female', 3),
('Knight the Pet of the streets', 145, 'dnd-15', 'white', 'male', 7),
('Horse the Horse of Siberia', 58, 'dog-19', 'brown', 'female', 6),
('Zebra the Lazy of the kitchen', 75, 'abc-1', 'black', 'male', 10),
('Horse the Lord of Japan', 159, 'dog-4', 'brown', 'male', 12),
('Horse the Dragon of United States', 199, 'dnd-17', 'white', 'female', 12),
('Horse the Pet of the streets', 105, 'abc-30', 'white', 'female', 6),
('Horse the Pet of America', 75, 'dog-3', 'brown', 'male', 1),
('Horse the Lord of Egypt', 86, 'dog-26', 'black', 'male', 6),
('Horse the Mighty of Japan', 144, 'dog-27', 'black', 'female', 15),
('Horse the Lord of America', 139, 'dnd-37', 'white', 'female', 3),
('Horse the Mighty of the streets', 113, 'cat-36', 'white', 'male', 14),
('Horse the Mighty of United States', 113, 'abc-37', 'brown', 'male', 19),
('Zebra the Samurai of United States', 174, 'dnd-4', 'white', 'male', 1),
('Horse the Samurai of United States', 58, 'abc-3', 'brown', 'male', 19),
('Zebra the Pet of the kitchen', 84, 'abc-16', 'black', 'male', 20),
('Zebra the Samurai of America', 137, 'cat-44', 'brown', 'male', 20),
('Zebra the Lord of the kitchen', 96, 'dnd-35', 'brown', 'female', 8),
('Horse the Dragon of Japan', 52, 'cat-3', 'white', 'female', 11),
('Zebra the Mighty of the streets', 172, 'dog-45', 'brown', 'female', 18),
('Zebra the Dragon of the kitchen', 152, 'dnd-40', 'white', 'female', 20),
('Zebra the Dragon of Egypt', 126, 'dnd-18', 'black', 'male', 14),
('Horse the Ruler of Japan', 152, 'abc-35', 'brown', 'female', 11),
('Zebra the Lazy of the kitchen', 121, 'dog-32', 'black', 'female', 17),
('Horse the Mighty of United States', 165, 'dog-2', 'white', 'female', 2),
('Zebra the Samurai of the kitchen', 96, 'dnd-6', 'brown', 'female', 2),
('Zebra the Ruler of the streets', 156, 'abc-28', 'black', 'female', 1),
('Zebra the Ruler of America', 74, 'dog-14', 'black', 'female', 16),
('Horse the Horse of Egypt', 135, 'dnd-36', 'white', 'male', 12),
('Horse the Dragon of United States', 67, 'abc-33', 'brown', 'male', 20),
('Knight the Horse of Japan', 110, 'cat-32', 'black', 'female', 12),
('Knight the Pet of Egypt', 134, 'cat-57', 'black', 'male', 9),
('Zebra the Pet of Siberia', 77, 'dnd-16', 'brown', 'female', 11),
('Zebra the Horse of United States', 135, 'cat-43', 'black', 'male', 11),
('Horse the Ruler of United States', 67, 'abc-11', 'black', 'male', 3),
('Knight the Lord of United States', 197, 'dog-40', 'white', 'male', 1),
('Zebra the Pet of Egypt', 197, 'dnd-22', 'black', 'male', 12),
('Horse the Ninja of the kitchen', 89, 'dog-21', 'brown', 'female', 1),
('Knight the Ninja of the streets', 103, 'dog-47', 'black', 'female', 5),
('Horse the Pet of America', 115, 'dog-24', 'brown', 'male', 9),
('Zebra the Lord of America', 174, 'dog-17', 'white', 'female', 14),
('Horse the Horse of United States', 94, 'cat-50', 'black', 'male', 14),
('Horse the Lazy of Egypt', 50, 'cat-6', 'brown', 'female', 5),
('Horse the Ninja of Egypt', 147, 'dog-5', 'brown', 'female', 18),
('Knight the Samurai of Japan', 67, 'cat-28', 'white', 'male', 4),
('Knight the Lazy of Siberia', 177, 'dog-9', 'black', 'male', 5),
('Horse the Ruler of Egypt', 108, 'cat-33', 'brown', 'male', 17),
('Horse the Samurai of America', 106, 'cat-38', 'brown', 'female', 13),
('Knight the Ruler of the streets', 188, 'dnd-29', 'white', 'female', 6),
('Zebra the Dragon of America', 88, 'abc-5', 'black', 'female', 9),
('Knight the Ninja of Japan', 101, 'dog-6', 'white', 'male', 14),
('Zebra the Lord of Siberia', 169, 'abc-51', 'black', 'male', 19),
('Knight the Ninja of Japan', 152, 'cat-47', 'brown', 'male', 17),
('Horse the Dragon of the kitchen', 175, 'dnd-45', 'black', 'male', 1),
('Horse the Pet of the streets', 75, 'dnd-28', 'brown', 'female', 20),
('Knight the Dragon of United States', 192, 'abc-49', 'black', 'female', 5),
('Horse the Mighty of America', 193, 'abc-42', 'black', 'female', 8),
('Knight the Ruler of Japan', 51, 'abc-50', 'brown', 'female', 3),
('Knight the Lazy of Egypt', 56, 'dog-53', 'brown', 'male', 7),
('Horse the Dragon of America', 82, 'cat-27', 'white', 'male', 8),
('Knight the Samurai of America', 160, 'dnd-7', 'white', 'female', 11),
('Knight the Lazy of the kitchen', 68, 'dog-33', 'white', 'female', 14),
('Horse the Samurai of America', 176, 'dnd-19', 'brown', 'male', 20),
('Knight the Samurai of Egypt', 172, 'cat-26', 'white', 'male', 11),
('Horse the Dragon of America', 113, 'dog-7', 'white', 'female', 3),
('Knight the Mighty of Siberia', 170, 'dnd-23', 'brown', 'male', 19),
('Zebra the Lazy of United States', 188, 'abc-36', 'white', 'female', 11);

create table Cat(
	name text,
	age int,
	breed text,
	sex int,
	count int
);

insert into Cat values
('Yoruichi the Ruler of United States', 12, 'British', 0, 6),
('Bella the Mighty of the kitchen', 14, 'Bengal', 1, 19),
('Lucy the Samurai of the streets', 12, 'Siberian', 0, 12),
('Felix the Pet of Japan', 18, 'American', 0, 10),
('Bella the Ruler of Egypt', 3, 'Munchkin', 0, 3),
('Koganei the Ruler of Siberia', 3, 'British', 1, 4),
('Nala the Cat of the kitchen', 20, 'American', 0, 10),
('Luna the Dragon of America', 11, 'Bengal', 1, 11),
('Lily the Samurai of Japan', 13, 'Siberian', 1, 18),
('Nala the Dragon of Egypt', 11, 'Munchkin', 1, 15),
('Luna the Lord of America', 3, 'Munchkin', 0, 16),
('Lily the Ruler of Egypt', 10, 'British', 0, 11),
('Lily the Lord of Egypt', 13, 'Bengal', 1, 11),
('Luna the Lazy of America', 4, 'American', 1, 2),
('Lily the Samurai of Japan', 10, 'American', 0, 5),
('Yoruichi the Mighty of United States', 15, 'American', 0, 2),
('Yoruichi the Ninja of Egypt', 17, 'Munchkin', 1, 12),
('Lily the Ninja of Siberia', 17, 'Bengal', 1, 5),
('Bella the Dragon of America', 3, 'Munchkin', 1, 1),
('Lucy the Cat of Japan', 20, 'Siberian', 1, 3),
('Yoruichi the Lord of Siberia', 6, 'British', 1, 12),
('Nala the Samurai of America', 5, 'Munchkin', 0, 17),
('Koganei the Ruler of the streets', 17, 'Siberian', 1, 7),
('Nala the Ninja of United States', 1, 'Bengal', 1, 14),
('Felix the Mighty of Siberia', 14, 'Munchkin', 0, 14),
('Kira the Pet of Siberia', 17, 'American', 0, 6),
('Bella the Dragon of United States', 20, 'Siberian', 1, 2),
('Yoruichi the Ruler of America', 14, 'Bengal', 0, 17),
('Lily the Ninja of America', 18, 'Munchkin', 0, 8),
('Bella the Cat of Japan', 3, 'Munchkin', 0, 14),
('Yoruichi the Mighty of Egypt', 16, 'British', 1, 16),
('Yoruichi the Ruler of Siberia', 14, 'British', 0, 7),
('Yoruichi the Ninja of Siberia', 14, 'Siberian', 0, 2),
('Yoruichi the Ninja of the streets', 13, 'Bengal', 0, 10),
('Felix the Lord of the kitchen', 19, 'American', 0, 3),
('Bella the Dragon of America', 12, 'British', 0, 8),
('Lucy the Cat of the streets', 15, 'British', 1, 4),
('Koganei the Cat of Siberia', 12, 'Siberian', 1, 2),
('Koganei the Mighty of America', 6, 'Bengal', 1, 18),
('Luna the Cat of Egypt', 5, 'American', 0, 15),
('Bella the Mighty of the streets', 12, 'Munchkin', 1, 17),
('Luna the Lazy of the streets', 7, 'American', 0, 5),
('Yoruichi the Ruler of Egypt', 15, 'Munchkin', 0, 2),
('Nala the Lord of the streets', 15, 'Munchkin', 0, 6),
('Bella the Lazy of America', 4, 'American', 1, 16),
('Nala the Cat of the kitchen', 14, 'Siberian', 1, 17),
('Luna the Ninja of Egypt', 10, 'Munchkin', 0, 14),
('Felix the Ruler of Japan', 13, 'Siberian', 0, 4),
('Kira the Mighty of Siberia', 16, 'Munchkin', 1, 1),
('Lucy the Samurai of the streets', 15, 'Siberian', 1, 14),
('Lily the Pet of Egypt', 16, 'Bengal', 0, 10),
('Nala the Samurai of United States', 10, 'Munchkin', 0, 14),
('Koganei the Mighty of Japan', 9, 'Bengal', 0, 20),
('Yoruichi the Ninja of Japan', 5, 'Siberian', 0, 16),
('Nala the Pet of the kitchen', 17, 'Siberian', 1, 13),
('Felix the Samurai of Japan', 13, 'British', 0, 10),
('Kira the Lazy of Japan', 14, 'Siberian', 1, 15),
('Koganei the Cat of Siberia', 5, 'Siberian', 0, 13),
('Lily the Cat of Siberia', 20, 'British', 1, 17),
('Felix the Ruler of the kitchen', 6, 'Siberian', 0, 12),
('Nala the Ruler of United States', 9, 'Bengal', 1, 16),
('Lucy the Mighty of Japan', 1, 'British', 1, 8),
('Luna the Mighty of Siberia', 15, 'American', 1, 4),
('Kira the Pet of the kitchen', 14, 'Munchkin', 0, 10),
('Luna the Ruler of Japan', 9, 'British', 1, 4),
('Lucy the Cat of United States', 18, 'Siberian', 1, 13),
('Yoruichi the Mighty of Egypt', 18, 'American', 1, 15),
('Nala the Ninja of America', 19, 'American', 0, 20),
('Kira the Ninja of Siberia', 3, 'Bengal', 0, 14),
('Lucy the Dragon of the kitchen', 10, 'Munchkin', 0, 14),
('Lucy the Pet of Japan', 13, 'Bengal', 0, 16),
('Koganei the Lord of United States', 4, 'American', 0, 15),
('Koganei the Ruler of the streets', 3, 'American', 0, 13),
('Nala the Lord of Siberia', 10, 'British', 1, 20),
('Yoruichi the Pet of Siberia', 1, 'Siberian', 0, 20),
('Felix the Ruler of the kitchen', 12, 'British', 0, 9),
('Lucy the Ruler of United States', 20, 'British', 0, 11),
('Nala the Lord of the streets', 6, 'American', 0, 8),
('Koganei the Pet of America', 3, 'British', 0, 2),
('Lucy the Ninja of Egypt', 3, 'Munchkin', 1, 12),
('Kira the Lazy of the kitchen', 2, 'British', 0, 6),
('Felix the Ninja of Egypt', 7, 'American', 1, 11),
('Nala the Dragon of United States', 11, 'Munchkin', 0, 12),
('Luna the Ninja of the kitchen', 12, 'Munchkin', 1, 3),
('Bella the Lord of the kitchen', 19, 'British', 1, 18),
('Felix the Cat of United States', 19, 'Bengal', 1, 12),
('Nala the Lazy of United States', 19, 'Munchkin', 0, 17),
('Kira the Dragon of United States', 7, 'Bengal', 0, 9),
('Felix the Samurai of United States', 12, 'Siberian', 1, 14),
('Lily the Ruler of United States', 6, 'Munchkin', 0, 5),
('Kira the Cat of United States', 7, 'Munchkin', 0, 19),
('Lily the Mighty of United States', 15, 'Bengal', 1, 3),
('Lily the Mighty of the streets', 1, 'American', 0, 11),
('Yoruichi the Ninja of the streets', 8, 'Munchkin', 1, 12),
('Yoruichi the Mighty of Siberia', 5, 'Bengal', 1, 8),
('Lily the Dragon of America', 8, 'Siberian', 0, 2),
('Bella the Cat of Siberia', 19, 'Siberian', 1, 11),
('Felix the Lord of America', 2, 'Bengal', 0, 17),
('Felix the Ruler of United States', 17, 'Bengal', 0, 20),
('Felix the Lord of Egypt', 17, 'American', 0, 12);
